export const urls = {
    // Genshin
    "genshin/characters": "https://api.irminsul.gg/v2/genshin/characters.json",
    "genshin/weapons": "https://api.irminsul.gg/v2/genshin/weapons.json",
    "genshin/artifacts": "https://api.irminsul.gg/v2/genshin/artifacts.json",
    "genshin/tcg": "https://api.irminsul.gg/v2/genshin/tcg.json",
    "genshin/tcg-keywords": "https://api.irminsul.gg/v2/genshin/tcg-keywords.json",
    "genshin/banner-characters": "https://api.irminsul.gg/v2/genshin/banner-characters.json",
    "genshin/banner-weapons": "https://api.irminsul.gg/v2/genshin/banner-weapons.json",
    "genshin/banner-chronicled": "https://api.irminsul.gg/v2/genshin/banner-chronicled.json",
    // HSR
    "hsr/characters": "https://api.irminsul.gg/v2/hsr/characters.json",
    "hsr/lightcones": "https://api.irminsul.gg/v2/hsr/weapons.json",
    "hsr/relics": "https://api.irminsul.gg/v2/hsr/relics.json",
    "hsr/banner-characters": "https://api.irminsul.gg/v2/hsr/banner-characters.json",
    "hsr/banner-weapons": "https://api.irminsul.gg/v2/hsr/banner-weapons.json",
    // WuWa
    "wuwa/resonators": "https://api.irminsul.gg/v2/wuwa/characters.json",
    "wuwa/weapons": "https://api.irminsul.gg/v2/wuwa/weapons.json",
    "wuwa/echoes": "https://api.irminsul.gg/v2/wuwa/echoes.json",
    "wuwa/banner-characters": "https://api.irminsul.gg/v2/wuwa/banner-characters.json",
    "wuwa/banner-weapons": "https://api.irminsul.gg/v2/wuwa/banner-weapons.json",
    // ZZZ
    "zzz/agents": "https://api.irminsul.gg/v2/zzz/characters.json",
    "zzz/w-engines": "https://api.irminsul.gg/v2/zzz/weapons.json",
    "zzz/drive-discs": "https://api.irminsul.gg/v2/zzz/drive-discs.json",
    "zzz/bangboos": "https://api.irminsul.gg/v2/zzz/bangboo.json",
    "zzz/banner-characters": "https://api.irminsul.gg/v2/zzz/banner-characters.json",
    "zzz/banner-weapons": "https://api.irminsul.gg/v2/zzz/banner-weapons.json",
    // Umamusume
    "uma/characters": "https://api.irminsul.gg/v2/uma/characters.json",
    "uma/character-profiles": "https://api.irminsul.gg/v2/uma/character-profiles.json",
    "uma/supports": "https://api.irminsul.gg/v2/uma/supports.json",
    "uma/skills": "https://api.irminsul.gg/v2/uma/skills.json",
    "uma/banner-characters": "https://api.irminsul.gg/v2/uma/banner-characters.json",
    "uma/banner-supports": "https://api.irminsul.gg/v2/uma/banner-supports.json",
    // Endfield
    "endfield/operators": "https://api.irminsul.gg/v2/endfield/characters.json",
    "endfield/weapons": "https://api.irminsul.gg/v2/endfield/weapons.json",
    "endfield/banner-characters": "https://api.irminsul.gg/v2/endfield/banner-characters.json",
    "endfield/banner-weapons": "https://api.irminsul.gg/v2/endfield/banner-weapons.json",
    // NTE
    "nte/espers": "https://api.irminsul.gg/v2/nte/characters.json",
    "nte/arcs": "https://api.irminsul.gg/v2/nte/weapons.json",
    "nte/cartridges": "https://api.irminsul.gg/v2/nte/cartridges.json",
    "nte/banner-characters": "https://api.irminsul.gg/v2/nte/banner-characters.json",
    "nte/banner-weapons": "https://api.irminsul.gg/v2/nte/banner-weapons.json",
};
